### ISSUE TITLE
Missing routes.py and config.py 

### ISSUE THREAD

**Issue by JocelynBe** [jesse-ai/project-template#1]
There are no `routes.py` and `config.py` in the project template directory which are required for jupyter 

Specifically, see research.init() https://github.com/jesse-ai/jesse/blob/fc8c76fa06fddbce177a0e29c01159274fc55385/jesse/research/__init__.py#L17

A simple test loading that init would prevent such issues in the future.
Also, having some releases would prevent from breaking the app for users

**Comment by saleh-mir** [comment]
Hey Jocelyn. Thank you for reporting this. I forgot about the research module. I need to refactor it to work without `config.py` and use `.env` instead. What do you need the `routes.py` for?

**Comment by saleh-mir** [comment]
The research works fine now.
