### ISSUE TITLE
great project but one question regarding databases

### ISSUE THREAD

**Issue by fahadshery** [jesse-ai/project-template#4]
Hi,

just came across this great project. But if I have my own `postgres` and `redid` servers running and wish to use them instead of spinning up new sub containers within your docker image. 

What's the best way to do that? i.e. should I amend your `Dockerfile` or just  add the IP addresses+ports number of my own servers in your `.env` file? 

Would it create the underline databases itself or should I create an empty database first and it will create tables in there on its on?

thanks

**Comment by saleh-mir** [comment]
I wish you had asked this question on discord or maybe even email because I don't check this repository for such questions To answer your question you need to edit your Docker compose file and the .env file
